### ISSUE TITLE
Lollipop 5.1 Decompile framework-res.apk and SystemUI.apk errors

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wting/android-apktool#782]
```
What steps will reproduce the problem?
1.decompile framework-res.apk
2.decompile SystemUI.apk
3.error log

What is the expected output? What do you see instead?
Both files can not be decompiled (recompiled could not be tried)

What version of the product are you using? On what operating system?
apktool_2.0.0rc4, win 8 (x32)(Java SE Development kit 8 update 40)

Please provide any additional information below.
//Error log:SystemUI.apk
W: Could not decode attr value, using undecoded value instead: ns=androidprv, 
name=primaryUserOnly, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=androidprv, 
name=primaryUserOnly, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=handleDrawable, value=0x7f02004a
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=outerRingDrawable, value=0x7f020050
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=pointDrawable, value=0x7f020046
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=outerRadius, value=0x7f0d00ed
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=glowRadius, value=0x7f0d0057
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=vibrationDuration, value=0x00000014
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=snapMargin, value=0x7f0d00ee
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=feedbackCount, value=0x00000001
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=firstItemOffset, value=0x7f0a003a
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=magneticTargets, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=prvandroid, 
name=allowScaling, value=0xffffffff
W: Could not decode attr value, using undecoded value instead: ns=internal, 
name=layout_maxHeight, value=0x00004001
W: Could not decode attr value, using undecoded value instead: ns=internal, 
name=layout_minHeight, value=0x00004001
Exception in thread "main" brut.androlib.err.UndefinedResObject: resource spec: 
0x0116006e
    at brut.androlib.res.data.ResPackage.getResSpec(ResPackage.java:59)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:57)
    at brut.androlib.res.data.ResTable.getResSpec(ResTable.java:53)
    at brut.androlib.res.decoder.ResAttrDecoder.decode(ResAttrDecoder.java:36)
    at brut.androlib.res.decoder.AXmlResourceParser.getAttributeValue(AXmlResourceParser.java:369)
    at org.xmlpull.v1.wrapper.classic.XmlPullParserDelegate.getAttributeValue(XmlPullParserDelegate.java:69)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.writeStartTag(StaticXmlSerializerWrapper.java:267)
    at org.xmlpull.v1.wrapper.classic.StaticXmlSerializerWrapper.event(StaticXmlSerializerWrapper.java:211)
    at brut.androlib.res.decoder.XmlPullStreamDecoder$1.event(XmlPullStreamDecoder.java:83)
    at brut.androlib.res.decoder.XmlPullStreamDecoder.decode(XmlPullStreamDecoder.java:141)
    at brut.androlib.res.decoder.ResStreamDecoderContainer.decode(ResStreamDecoderContainer.java:33)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:114)
    at brut.androlib.res.decoder.ResFileDecoder.decode(ResFileDecoder.java:99)
    at brut.androlib.res.AndrolibResources.decode(AndrolibResources.java:339)
    at brut.androlib.Androlib.decodeResourcesFull(Androlib.java:133)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:104)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)
//-------
//Error log:framework-res.apk
Exception in thread "main" brut.androlib.AndrolibException: Invalid value type: 
0
    at brut.androlib.res.data.value.ResValueFactory.factory(ResValueFactory.java:64)
    at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:242)
    at brut.androlib.res.decoder.ARSCDecoder.readComplexEntry(ARSCDecoder.java:230)
    at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:200)
    at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:188)
    at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:156)
    at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:113)
    at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
    at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
    at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:622)
    at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:73)
    at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:65)
    at brut.androlib.Androlib.getResTable(Androlib.java:63)
    at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
    at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
    at brut.apktool.Main.cmdDecode(Main.java:165)
    at brut.apktool.Main.main(Main.java:81)

//-------
Any suggestions appreciated,
Kind regards


```

Original issue reported on code.google.com by `biont...@gmail.com` on 13 Mar 2015 at 8:39

Attachments:
- [framework-res.7z](https://storage.googleapis.com/google-code-attachments/android-apktool/issue-782/comment-0/framework-res.7z)
- [SystemUI.7z](https://storage.googleapis.com/google-code-attachments/android-apktool/issue-782/comment-0/SystemUI.7z)

**Comment by Hanger1** [comment]
Same error Cant decompile framework-res.apk from Lollipop 5.1
